### ISSUE TITLE
Windows version tries to open multiple mod files

### ISSUE THREAD

**Issue by Jaysyn904** [hendrikgit/nwn_sqlite#4]
I'm not sure what I'm doing wrong here & the readme is severely lacking.

My command line:
```
C:\NWN Work\nwn_sqlite>nwn_sqlite -withkey -o:nwnds_export.sqlite3  "C:\Users\Jason\Documents\Neverwinter Nights\modules\nwn_dark_sun.mod"  "C:\Games\Steam\steamapps\common\Neverwinter Nights\lang\es\data"  "C:\Games\Steam\steamapps\common\Neverwinter Nights\data"  "C:\Users\Jason\Documents\Neverwinter Nights\tlk"  "C:\Users\Jason\Documents\Neverwinter Nights\hak"
```

The output:
```
Adding dialog.tlk: C:\Games\Steam\steamapps\common\Neverwinter Nights\lang\es\data\dialog.tlk
Adding key: C:\Games\Steam\steamapps\common\Neverwinter Nights\data\nwn_base.key
Only one .mod file at a time is supported: C:\Users\Jason\Documents\Neverwinter Nights\modules\nwn_dark_sun.mod, C:\Users\Jason\Documents\Neverwinter Nights\hak\NUI_menus.mod
```

**Comment by hendrikgit** [comment]
Hello.

Thanks for the command and output.

It is as the output of the tool says, only one .mod file is supported. This could be changed of course but it made sense for my usage at the time.

It looks like your main mod is the one you specified directly by path `C:\Users\Jason\Documents\Neverwinter Nights\modules\nwn_dark_sun.mod`. According to the output you have another .mod file in you hak folder, `NUI_menus.mod`. Maybe it is not supposed to be there, since it is a hak folder, and you could move it.

Alternatively try modifying your command line to say `"C:\Users\Jason\Documents\Neverwinter Nights\hak\*.hak"` instead of `"C:\Users\Jason\Documents\Neverwinter Nights\hak"` so that only the *.hak files are read and not the .mod that is in there.

**Comment by Jaysyn904** [comment]
I moved the misplaced .mod file.

It appears that you can't use the NWN doc dir path for this as it tries to ingest every single hak file in the folder, even if they aren't associated with the module.  I do understand what needs to be done now however.

Seems like it should only care about what is in the ifo file when processing a module.
